# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

clone_depth: 5

cache:
- x86_64-7.3.0-release-win32-seh-rt_v5-rev0.7z
- i686-7.3.0-release-win32-dwarf-rt_v5-rev0.7z

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: QOuiktPDkbsZmX/lOynJrOrrpR09k8C14rSPRjGnohwrgc4Ee97qjoEQpODFb1ZK
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - MINGW_TARGET: mingw64
  - MINGW_TARGET: mingw32

build_script:
- powershell -NoProfile -ExecutionPolicy Bypass -file build.ps1 -target %MINGW_TARGET%

artifacts:
- path: build\mingw\drmingw-*.7z

deploy:
  provider: GitHub
  auth_token:
    secure: E46gT6yNIKl9L5tmcJdNY6NJ+KXmaNV7U19ZpNjz2R8U2dRUwBceMKqCHE5cs3JA
  artifact: /.*\.7z/
  on:
    appveyor_repo_tag: true
